version: '3.8'

services:
  fastapi:
    build: .
    image: tp1_mlops_ft
    container_name: fastapi_app
    ports:
      - "5462:5462"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
