name: CD Pipeline for FastAPI Project

# Trigger the workflow on push to main branch
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Build the Docker image
      - name: Build Docker Image
        run: docker compose build fastapi

      # Step 3: Tag the Docker image
        # Replace 'tagname' with the appropriate tag you want to use.
      - name: Tag Docker Image
        run: docker tag tp1_mlops_ft flotigoulet/tp1_mlops:latest

      # Step 4: Log in to Docker Hub
      - name: Docker Login
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

      # Step 5: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: docker push flotigoulet/tp1_mlops:latest

      # Step 6: Install sshpass
      - name: Install sshpass
        run: sudo apt-get update && sudo apt-get install -y sshpass

      # Step 7: Deploy to Remote Server using sshpass
      - name: Deploy to Remote Server using sshpass
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ubuntu@20.86.55.5 << 'EOF'
            docker pull flotigoulet/tp1_mlops:latest
            docker run -p 5462:5462 flotigoulet/tp1_mlops
          EOF